
// Template Auto generated by makeMockComponents.js
// To overwrite the mock manually add path to ignore array. 
import React from 'react';
const mock = props => (
  <div data-test-id={'ComponentTwo.test'} {...props}>
    <p>Mock ComponentTwo.test</p>
     {props.children}
  </div>
);

export default mock;