
// Template Auto generated by makeMockComponents.js
// To overwrite the mock manually add path to ignore array. 
import React from 'react';
const mock: React.FC = props => (
  <div data-test-id={'ComponentOne'} {...props}>
    <p>Mock ComponentOne</p>
     {props.children}
  </div>
);

export default mock;