export const mockComponentTS = (name: string) => `
// Template Auto generated by makeMockComponents.js
// To overwrite the mock manually add path to ignore array. 
import React from 'react';
const mock: React.FC<any> = props => (
  <div data-test-id={'${name}'} {...props}>
    <p>Mock ${name}</p>
     {props.children}
  </div>
);

export default mock;`;

